[package]
name = "fs-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.22", features = ["derive", "cargo"] }
env_logger = "0.9.1"
fuser = "0.11.1"
libc = "0.2.133"
